#define MAX_BYTE 256
#define MAX_DIRECTORIES 32
#define MAX_FILES 32
#define MAX_FILESYSTEM_ITEM_COUNT 32
#define MAX_DIRECTORYNAME 15
#define MAX_FILENAME 15
#define MAX_SECTORS 16
#define MAX_PATHNAME 512
#define SIZE_SECTOR 512
#define SIZE_DIR_ENTRY 16
#define LOC_ARGS_SECTOR 512
#define LOC_MAP_SECTOR 256
#define LOC_DIR_SECTOR 257
#define LOC_FILE_SECTOR 258
#define LOC_SECTOR_SECTOR 259
#define ERROR_INTERNAL_WRITEFILE_INSUFFICIENT_SECTORS 0
#define ERROR_INSUFFICIENT_SECTORS -4
#define ERROR_INSUFFICIENT_ENTRIES -3
#define ERROR_ALREADY_EXISTS -2
#define ERROR_NOT_FOUND -1
#define ERROR_INSUFFICIENT_SEGMENTS -2
#define WRITEFILE_SUCCES 1
#define SUCCESS 0
#define EMPTY 0x00
#define USED 0xFF
#define ROOT 0xFF

#define SHELL_MAX_PART 35
#define SHELL_MAX_STRINGLENGTH 35

#define SIZE_EMSG_ENTRY 16
#define EMSG_NOT_FOUND 0
#define EMSG_INSUFFICIENT 1
#define EMSG_SECTORS 2
#define EMSG_ENTRIES 3
#define EMSG_ALREADY_EXIST 4
#define EMSG_PROGRAM 5
#define EMSG_TOO_MANY_ARGS 6
#define EMSG_INVALID_PATH 7
#define EMSG_IO_ERROR 8

#define boolean unsigned char
#define true 1
#define false 0